import java.awt.Toolkit;
import java.awt.Color;
import java.awt.SystemColor;
import java.awt.Font;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.SwingConstants;


/**
 *
 * @author pc
 */
public class Eneargycalculator extends javax.swing.JFrame {

    /**
     * Creates new form Interface
     */
    public Eneargycalculator() {
    	setTitle("Energy Calculator");
    	setIconImage(Toolkit.getDefaultToolkit().getImage("C:\\Users\\riche\\OneDrive\\Desktop\\energy-icon-for-your-website-design-logo-app-ui-free-vector.jpg"));
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        jTextField1.setHorizontalAlignment(SwingConstants.CENTER);
        jTextField2 = new javax.swing.JTextField();
        jTextField2.setHorizontalAlignment(SwingConstants.CENTER);
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton3.setForeground(new Color(220, 20, 60));
        jButton4 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel5.setFont(new Font("Verdana", Font.ITALIC, 13));

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(Color.ORANGE);

        jLabel1.setFont(new Font("DialogInput", Font.BOLD, 28)); // NOI18N
        jLabel1.setForeground(new Color(0, 255, 255));
        jLabel1.setText("Energy Calculator");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1Layout.setHorizontalGroup(
        	jPanel1Layout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(Alignment.LEADING, jPanel1Layout.createSequentialGroup()
        			.addGap(150)
        			.addComponent(jLabel1)
        			.addContainerGap(170, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
        	jPanel1Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addGap(21)
        			.addComponent(jLabel1)
        			.addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel1.setLayout(jPanel1Layout);

        jComboBox1.setFont(new Font("Dubai", Font.PLAIN, 15)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Joules", "Food Calories", "Thermal Calories" }));

        jComboBox2.setFont(new Font("Dubai", Font.PLAIN, 15)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Food Calories", "Thermal Calories", "Joules" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jTextField1.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        jTextField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTextField2.setEditable(false);
        jTextField2.setBackground(new Color(255, 228, 196));
        jTextField2.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        jTextField2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButton2.setBackground(Color.ORANGE);
        jButton2.setFont(new java.awt.Font("Inter", 1, 18)); // NOI18N
        jButton2.setForeground(new Color(0, 255, 255));
        jButton2.setText("Convert");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(204, 204, 204));
        jLabel2.setFont(new Font("Dubai Medium", Font.BOLD, 15)); // NOI18N
        jLabel2.setForeground(new Color(0, 0, 139));
        jLabel2.setText("From :");

        jLabel3.setFont(new Font("Dubai Medium", Font.BOLD, 15)); // NOI18N
        jLabel3.setForeground(new Color(0, 0, 139));
        jLabel3.setText("To :");

        jLabel4.setFont(new Font("Dubai Medium", Font.BOLD, 15)); // NOI18N
        jLabel4.setForeground(new Color(0, 0, 139));
        jLabel4.setText("Enter Values :");

        jLabel6.setFont(new Font("Dubai Medium", Font.BOLD, 15)); // NOI18N
        jLabel6.setForeground(new Color(0, 0, 139));
        jLabel6.setText("Result");

        jButton3.setFont(new Font("Dialog", Font.BOLD, 15)); // NOI18N
        jButton3.setText("Clear");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new Font("Dialog", Font.BOLD | Font.ITALIC, 12)); // NOI18N
        jButton4.setText("Exit");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel5.setForeground(new java.awt.Color(153, 153, 153));
        jLabel5.setText("Project by : Zannatul Naim Tamanna   ID: 0322310205101053");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, 522, Short.MAX_VALUE)
        		.addGroup(layout.createSequentialGroup()
        			.addGap(59)
        			.addGroup(layout.createParallelGroup(Alignment.TRAILING)
        				.addComponent(jLabel5)
        				.addGroup(layout.createSequentialGroup()
        					.addGroup(layout.createParallelGroup(Alignment.LEADING)
        						.addComponent(jLabel2)
        						.addComponent(jLabel3)
        						.addComponent(jLabel4)
        						.addComponent(jLabel6))
        					.addGroup(layout.createParallelGroup(Alignment.LEADING, false)
        						.addGroup(layout.createSequentialGroup()
        							.addGap(46)
        							.addGroup(layout.createParallelGroup(Alignment.TRAILING, false)
        								.addGroup(layout.createSequentialGroup()
        									.addComponent(jButton4, GroupLayout.PREFERRED_SIZE, 53, GroupLayout.PREFERRED_SIZE)
        									.addPreferredGap(ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        									.addComponent(jButton3))
        								.addComponent(jButton2, Alignment.LEADING, GroupLayout.PREFERRED_SIZE, 218, GroupLayout.PREFERRED_SIZE)
        								.addGroup(Alignment.LEADING, layout.createParallelGroup(Alignment.TRAILING, false)
        									.addComponent(jComboBox1, Alignment.LEADING, 0, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        									.addComponent(jComboBox2, Alignment.LEADING, 0, 205, Short.MAX_VALUE))))
        						.addGroup(Alignment.TRAILING, layout.createSequentialGroup()
        							.addPreferredGap(ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        							.addComponent(jTextField1, GroupLayout.PREFERRED_SIZE, 168, GroupLayout.PREFERRED_SIZE)
        							.addGap(26))
        						.addGroup(Alignment.TRAILING, layout.createSequentialGroup()
        							.addPreferredGap(ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        							.addComponent(jTextField2, GroupLayout.PREFERRED_SIZE, 169, GroupLayout.PREFERRED_SIZE)
        							.addGap(24)))))
        			.addContainerGap(88, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        			.addGap(29)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jComboBox1, GroupLayout.PREFERRED_SIZE, 35, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jLabel2))
        			.addGap(18)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jComboBox2, GroupLayout.PREFERRED_SIZE, 35, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jLabel3))
        			.addGap(18)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jLabel4)
        				.addComponent(jTextField1, GroupLayout.PREFERRED_SIZE, 56, GroupLayout.PREFERRED_SIZE))
        			.addGap(18)
        			.addComponent(jButton2, GroupLayout.PREFERRED_SIZE, 46, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jLabel6)
        				.addComponent(jTextField2, GroupLayout.PREFERRED_SIZE, 62, GroupLayout.PREFERRED_SIZE))
        			.addGap(18)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jButton3)
        				.addComponent(jButton4, GroupLayout.PREFERRED_SIZE, 26, GroupLayout.PREFERRED_SIZE))
        			.addPreferredGap(ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
        			.addComponent(jLabel5)
        			.addGap(27))
        );
        getContentPane().setLayout(layout);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       jTextField1.setText("");
       jTextField2.setText("");
                              
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      String box1=(String)jComboBox1.getSelectedItem();
      String box2=(String)jComboBox2.getSelectedItem();
      
      if(box1.equals("Joules") && box2.equals("Thermal Calories"))
       {
           double j = Double.parseDouble(jTextField1.getText());
           
           double t = (double)(j*0.239006);
           
           jTextField2.setText(String.valueOf(t));
       }
       else if(box1.equals("Joules") && box2.equals("Food Calories"))
       {
           double j = Double.parseDouble(jTextField1.getText());
           
           double f = (double)(j*0.000239 );
           
           jTextField2.setText(String.valueOf(f));
       }
       else if(box1.equals("Joules") && box2.equals("Joules"))
       {
           double j = Double.parseDouble(jTextField1.getText());
         
           jTextField2.setText(String.valueOf(j));
       }

       if(box1.equals("Thermal Calories") && box2.equals("Joules"))
       {
           double t = Double.parseDouble(jTextField1.getText());
           
           double j = (double)(t*4.184);
           
           jTextField2.setText(String.valueOf(j));
       }
       else if(box1.equals("Thermal Calories") && box2.equals("Food Calories"))
       {
           double t = Double.parseDouble(jTextField1.getText());
           
           double f = (double)(t*0.001);
           
           jTextField2.setText(String.valueOf(f));
       }
       else if(box1.equals("Thermal Calories") && box2.equals("Thermal Calories"))
       {
           double t = Double.parseDouble(jTextField1.getText());
         
           jTextField2.setText(String.valueOf(t));
       }
       

       if(box1.equals("Food Calories") && box2.equals("Thermal Calories"))
       {
           double f = Double.parseDouble(jTextField1.getText());
           
           double t = (double)(f*1000);
           
           jTextField2.setText(String.valueOf(t));
       }
       else if(box1.equals("Food Calories") && box2.equals("Joules"))
       {
           double t = Double.parseDouble(jTextField1.getText());
           
           double j = (double)(t*4184);
           
           jTextField2.setText(String.valueOf(j));
       }
       else if(box1.equals("Food Calories") && box2.equals("Food Calories"))
       {
           double f = Double.parseDouble(jTextField1.getText());
         
           jTextField2.setText(String.valueOf(f));
       }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Eneargycalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Eneargycalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Eneargycalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Eneargycalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Eneargycalculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
